# HTTP (Tomcat) port
server:
  port: 8280

#Application name
spring:
  application:
    name: zuul-server

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
