# HTTP (Tomcat) port
server:
  port: 8091

#Application name
spring:
  application:
    name: user-provider

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
